[default]
address = "127.0.0.1"
port = 8000

log_level = "info"
log = "kelpietipping.log"

[release]
address = "127.0.0.1"
port = 80

log_level = "warn"
log = "kelpietipping.log"

[default.databases.kelpie_db]
url = "postgres://shartrec:laverda21@localhost:5432/kelpie_tips"