[default]
address = "127.0.0.1"
port = 8000

log_level = "normal"

[release]
address = "127.0.0.1"
port = 80

log_level = "warn"

[default.databases.kelpie_db]
url = "postgres://shartrec:laverda21@localhost:5432/kelpie_tips"